"""empty message

Revision ID: 3eb0acbc946e
Revises: eab0c4e91a2e
Create Date: 2018-04-15 15:08:44.009829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eb0acbc946e'
down_revision = 'eab0c4e91a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifttable', sa.Column('origin_path', sa.String(length=255), nullable=False))
    op.add_column('shifttable', sa.Column('thumbnail_path', sa.String(length=255), nullable=False))
    op.drop_column('shifttable', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifttable', sa.Column('path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('shifttable', 'thumbnail_path')
    op.drop_column('shifttable', 'origin_path')
    # ### end Alembic commands ###
