"""empty message

Revision ID: 3eec7cbb9ac0
Revises: 7f8cebe37dd6
Create Date: 2018-04-16 03:37:20.378542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eec7cbb9ac0'
down_revision = '7f8cebe37dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifttable', 'origin_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shifttable', 'thumbnail_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifttable', 'thumbnail_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('shifttable', 'origin_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
