"""empty message

Revision ID: 6400f822d6de
Revises: 5b9b9d8b0878
Create Date: 2018-10-15 13:05:37.553513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6400f822d6de'
down_revision = '5b9b9d8b0878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifttable', 'end')
    op.drop_column('shifttable', 'start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifttable', sa.Column('start', mysql.TIME(), nullable=True))
    op.add_column('shifttable', sa.Column('end', mysql.TIME(), nullable=True))
    # ### end Alembic commands ###
