"""empty message

Revision ID: 7f97e7f7afc6
Revises: abb53e438dc1
Create Date: 2018-06-20 15:12:07.766845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f97e7f7afc6'
down_revision = 'abb53e438dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('end', sa.Time(), nullable=True))
    op.add_column('shift', sa.Column('start', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift', 'start')
    op.drop_column('shift', 'end')
    # ### end Alembic commands ###
