# Uncomment the next line to define a global platform for your project
  platform :ios, '11.4'

target 'Shifree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'AlamofireImage'
pod 'Eureka'
pod 'FloatingActionSheetController'
pod 'FSCalendar'
pod 'KeychainAccess'
pod 'MKColorPicker'
pod 'NVActivityIndicatorView'
pod 'PopupDialog'
pod 'PromiseKit'
pod 'ScrollableGraphView'
pod 'StatusProvider'
pod 'SwiftyJSON'
pod 'TinyConstraints'
pod 'Charts'

swift4_names = [
	'MKColorPicker'
]

swift_enforce = [
	'Eureka'
]

post_install do |installer|
	installer.pods_project.targets.each do |target|
  		if swift_enforce.include? target.name
			target.build_configurations.each do |config|
			config.build_settings['SWIFT_ENFORCE_EXCLUSIVE_ACCESS'] = 'off'
		end
	end

		if swift4_names.include? target.name
			target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '4.0'
		end
	end
end
end

end
