# Uncomment the next line to define a global platform for your project
  platform :ios, '11.4'

target 'Parjob' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  
  
pod 'AlamofireImage', '~> 3.3'
pod 'Alamofire'
pod 'PromiseKit'
pod 'KeychainAccess'
pod 'SwiftyJSON'
pod 'TinyConstraints', :git => 'https://github.com/roberthein/TinyConstraints.git', :branch => 'release/swift-4'
pod 'Eureka'
pod 'PopupDialog', '~> 0.8'
pod 'ScrollableGraphView', '~> 4.0'
pod 'StatusProvider'
pod 'FloatingActionSheetController'
pod 'NVActivityIndicatorView'
pod 'MKColorPicker'
pod 'FSCalendar'
end
