# Uncomment the next line to define a global platform for your project
  platform :ios, '11.4'

target 'Parjob' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.5'
  pod 'KeychainAccess'
  pod 'TinyConstraints', :git => 'https://github.com/roberthein/TinyConstraints.git', :branch => 'Release_2.1.2'
  pod 'PromiseKit', '~> 6.0'
  pod 'PopupDialog', '0.5.4'
  pod 'FSCalendar'
  pod "MKColorPicker"
  pod 'ScrollableGraphView'
  pod 'AlamofireImage', '~> 3.3'
  pod 'NVActivityIndicatorView'
  pod 'StatusProvider'
  pod 'FloatingActionSheetController'
end
