"""empty message

Revision ID: 211dcd0f91c8
Revises: 66b924bd3640
Create Date: 2018-06-14 16:15:29.155272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211dcd0f91c8'
down_revision = '66b924bd3640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='shift')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'shift', ['name'], unique=True)
    # ### end Alembic commands ###
