"""empty message

Revision ID: 4dfd9e2b9078
Revises: c662902d5306
Create Date: 2018-04-01 04:52:02.055979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dfd9e2b9078'
down_revision = 'c662902d5306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colorscheme', sa.Column('hex', sa.String(length=255), nullable=False))
    op.drop_column('colorscheme', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colorscheme', sa.Column('color', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('colorscheme', 'hex')
    # ### end Alembic commands ###
