"""empty message

Revision ID: 66b924bd3640
Revises: 9a93e76058a9
Create Date: 2018-06-14 16:14:37.826863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b924bd3640'
down_revision = '9a93e76058a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shift', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift', type_='unique')
    # ### end Alembic commands ###
