"""empty message

Revision ID: 6a0731003ed6
Revises: f86a9234900a
Create Date: 2018-04-03 01:58:18.817942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0731003ed6'
down_revision = 'f86a9234900a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'created_at')
    # ### end Alembic commands ###
