"""empty message

Revision ID: 9a93e76058a9
Revises: 3eec7cbb9ac0
Create Date: 2018-04-16 04:35:23.041396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a93e76058a9'
down_revision = '3eec7cbb9ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'program_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('program_path', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
