"""empty message

Revision ID: c662902d5306
Revises: 025c43e5d951
Create Date: 2018-04-01 04:43:04.447177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c662902d5306'
down_revision = '025c43e5d951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colorscheme', sa.Column('shift_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'colorscheme', 'shiftcategory', ['shift_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colorscheme', type_='foreignkey')
    op.drop_column('colorscheme', 'shift_category_id')
    # ### end Alembic commands ###
