"""empty message

Revision ID: d532a371825d
Revises: c2907b8506c1
Create Date: 2018-07-05 02:50:57.005089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd532a371825d'
down_revision = 'c2907b8506c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_authed', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_authed')
    # ### end Alembic commands ###
