"""empty message

Revision ID: eee4c5a77aa4
Revises: 7f97e7f7afc6
Create Date: 2018-06-22 11:13:33.047962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee4c5a77aa4'
down_revision = '7f97e7f7afc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('default_day_shift_threshold', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('default_join_threshold', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('default_same_line_threshold', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('default_username_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'default_username_threshold')
    op.drop_column('company', 'default_same_line_threshold')
    op.drop_column('company', 'default_join_threshold')
    op.drop_column('company', 'default_day_shift_threshold')
    # ### end Alembic commands ###
